scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      scrape_timeout: 4s
      static_configs:
        - targets: ['host.docker.internal:8081']
          labels:
            service: 'service-layer'
            group: 'production'
        - targets: ['host.docker.internal:9216']
          labels:
            service: 'database'
            group: 'production'
