FROM       golang:alpine as builder

RUN apk --no-cache add curl git make perl git
RUN curl -s https://glide.sh/get | sh

RUN mkdir -p /go/src/github.com/percona/mongodb_exporter && cd /go/src/github.com/percona/mongodb_exporter && git clone https://github.com/percona/mongodb_exporter.git .
RUN cd /go/src/github.com/percona/mongodb_exporter && make build

FROM       alpine:3.4
EXPOSE     9001

RUN apk add --update ca-certificates
COPY --from=builder /go/src/github.com/percona/mongodb_exporter/bin/mongodb_exporter /usr/local/bin/mongodb_exporter

ENTRYPOINT [ "mongodb_exporter" ]
